In [8]:
import pandas as pd

In [9]:
df=pd.read_csv('stp.csv')
df

,gender,race,parental,lunch,test_preparation_course,mathscore,readingscore,writingscore
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [10]:
from sklearn.preprocessing import LabelEncoder#preprocessing
enc = LabelEncoder()
enc.fit(df.gender)
df.gender = enc.transform(df.gender)
enc.fit(df.race)
df.race = enc.transform(df.race)
enc.fit(df.parental)
df.parental = enc.transform(df.parental)
enc.fit(df.lunch)
df.lunch = enc.transform(df.lunch)
enc.fit(df.test_preparation_course)
df.test_preparation_course = enc.transform(df.test_preparation_course)
df

,gender,race,parental,lunch,test_preparation_course,mathscore,readingscore,writingscore
0,0,1,1,1,1,72,72,74
1,0,2,4,1,0,69,90,88
2,0,1,3,1,1,90,95,93
3,1,0,0,0,1,47,57,44
4,1,2,4,1,1,76,78,75
...,...,...,...,...,...,...,...,...
995,0,4,3,1,0,88,99,95
996,1,2,2,0,1,62,55,55
997,0,2,2,0,0,59,71,65
998,0,3,4,1,0,68,78,77
999,0,3,4,0,1,77,86,86

In [29]:
x=df.iloc[:,[0,1,2,3,4]]
y=df.iloc[:,[5,6,7]]

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,random_state=1)

In [32]:
from sklearn.tree import DecisionTreeRegressor

In [33]:
dtreg1=DecisionTreeRegressor()
dtreg1.fit(xtrain,ytrain)
ypred_1=dtreg1.predict(xtest)
ypred_1

array([[ 67.75      ,  61.25      ,  58.75      ],
       [ 40.        ,  56.        ,  51.75      ],
       [ 58.5       ,  71.75      ,  67.75      ],
       [ 48.5       ,  58.        ,  56.        ],
       [ 61.66666667,  69.33333333,  67.66666667],
       [ 54.33333333,  68.        ,  65.        ],
       [ 54.33333333,  68.        ,  65.        ],
       [ 67.5       ,  56.        ,  46.5       ],
       [ 59.        ,  54.        ,  51.        ],
       [ 68.8       ,  64.2       ,  63.        ],
       [ 64.2       ,  60.        ,  58.        ],
       [ 75.        ,  88.        ,  85.        ],
       [ 76.        ,  79.85714286,  80.57142857],
       [ 58.9       ,  68.1       ,  66.4       ],
       [ 68.66666667,  71.        ,  66.        ],
       [ 73.7       ,  84.        ,  84.9       ],
       [ 79.        ,  79.        ,  78.        ],
       [ 59.75      ,  70.75      ,  71.        ],
       [ 69.57142857,  76.71428571,  80.14285714],
       [ 66.07142857,  72.42857143,  74.14285714],
       [ 80.        ,  78.        ,  81.        ],
       [ 69.44444444,  80.        ,  83.11111111],
       [ 61.66666667,  69.33333333,  67.66666667],
       [ 63.        ,  58.8       ,  56.2       ],
       [ 48.5       ,  58.        ,  56.        ],
       [ 66.07142857,  72.42857143,  74.14285714],
       [ 51.5       ,  66.75      ,  64.25      ],
       [ 49.        ,  51.5       ,  48.5       ],
       [ 71.        ,  83.        ,  77.        ],
       [ 79.        ,  89.        ,  89.        ],
       [ 61.5       ,  57.        ,  55.5       ],
       [ 58.9       ,  68.1       ,  66.4       ],
       [ 54.        ,  52.8       ,  48.6       ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 58.9       ,  68.1       ,  66.4       ],
       [ 76.        ,  79.6       ,  78.4       ],
       [ 74.4       ,  81.6       ,  84.4       ],
       [ 80.        ,  79.        ,  79.        ],
       [ 62.25      ,  58.125     ,  56.        ],
       [ 55.        ,  60.5       ,  60.5       ],
       [ 79.        ,  78.66666667,  79.        ],
       [ 50.        ,  56.        ,  54.        ],
       [ 73.5       ,  81.25      ,  85.25      ],
       [ 67.        ,  61.        ,  68.        ],
       [ 56.5       ,  63.75      ,  61.75      ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 61.66666667,  69.33333333,  67.66666667],
       [ 64.26666667,  72.2       ,  71.        ],
       [ 63.        ,  58.8       ,  56.2       ],
       [ 68.        ,  75.        ,  73.        ],
       [ 84.        ,  80.16666667,  79.33333333],
       [ 70.625     ,  64.75      ,  60.625     ],
       [ 72.125     ,  78.75      ,  77.125     ],
       [ 77.2       ,  71.6       ,  69.8       ],
       [ 71.        ,  76.        ,  83.        ],
       [ 57.        ,  62.        ,  58.        ],
       [ 69.44444444,  80.        ,  83.11111111],
       [ 67.57142857,  74.57142857,  77.        ],
       [ 64.2       ,  60.        ,  58.        ],
       [ 68.        ,  75.        ,  73.        ],
       [ 64.71428571,  62.28571429,  56.        ],
       [ 63.5       ,  56.66666667,  54.16666667],
       [ 45.        ,  47.        ,  49.        ],
       [ 71.        ,  76.        ,  70.        ],
       [ 87.        ,  74.        ,  70.        ],
       [ 58.        ,  75.        ,  77.        ],
       [ 80.        ,  78.        ,  81.        ],
       [ 55.        ,  60.5       ,  60.5       ],
       [ 66.        ,  74.66666667,  78.66666667],
       [ 48.33333333,  59.        ,  53.66666667],
       [ 70.75      ,  85.25      ,  88.        ],
       [ 70.625     ,  64.75      ,  60.625     ],
       [ 66.5       ,  72.75      ,  70.75      ],
       [ 69.83333333,  64.25      ,  64.91666667],
       [ 82.66666667,  80.        ,  75.33333333],
       [ 75.5       ,  67.25      ,  63.        ],
       [ 69.33333333,  66.        ,  69.        ],
       [ 75.5       ,  74.        ,  68.5       ],
       [ 73.27272727,  68.72727273,  66.72727273],
       [ 70.625     ,  64.75      ,  60.625     ],
       [ 80.4       ,  79.        ,  82.4       ],
       [ 58.9       ,  68.1       ,  66.4       ],
       [ 69.83333333,  64.25      ,  64.91666667],
       [ 62.        ,  65.5       ,  67.25      ],
       [ 77.6       ,  84.        ,  88.2       ],
       [ 45.        ,  54.        ,  55.        ],
       [ 52.66666667,  61.16666667,  60.        ],
       [ 59.5       ,  63.5       ,  63.        ],
       [ 53.        ,  65.25      ,  63.75      ],
       [ 44.55555556,  57.77777778,  53.44444444],
       [ 60.25      ,  67.        ,  67.125     ],
       [ 73.5       ,  81.25      ,  85.25      ],
       [ 68.        ,  75.        ,  73.        ],
       [ 64.9       ,  57.9       ,  54.7       ],
       [ 54.66666667,  66.33333333,  69.66666667],
       [ 82.66666667,  80.        ,  75.33333333],
       [ 72.71428571,  68.71428571,  65.57142857],
       [ 74.5       ,  77.5       ,  71.75      ],
       [ 56.5       ,  63.75      ,  61.75      ],
       [ 72.71428571,  68.71428571,  65.57142857],
       [ 59.        ,  65.        ,  65.66666667],
       [100.        ,  96.        ,  86.        ],
       [ 57.        ,  64.        ,  65.5       ],
       [ 57.        ,  75.        ,  73.        ],
       [ 57.66666667,  55.66666667,  50.        ],
       [ 54.33333333,  68.        ,  65.        ],
       [ 61.66666667,  69.33333333,  67.66666667],
       [ 73.        ,  63.        ,  68.        ],
       [ 61.5       ,  57.        ,  55.5       ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 74.6       ,  63.2       ,  63.        ],
       [ 59.75      ,  70.75      ,  71.        ],
       [ 75.66666667,  64.        ,  60.66666667],
       [ 54.33333333,  68.        ,  65.        ],
       [ 78.5       ,  71.25      ,  71.25      ],
       [ 58.        ,  75.        ,  77.        ],
       [ 68.        ,  75.        ,  73.        ],
       [ 71.83333333,  63.        ,  60.16666667],
       [ 70.25      ,  83.5       ,  83.25      ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 65.66666667,  61.66666667,  64.33333333],
       [ 59.        ,  54.        ,  51.        ],
       [ 62.        ,  61.        ,  55.        ],
       [ 58.        ,  75.        ,  77.        ],
       [ 82.66666667,  80.        ,  75.33333333],
       [ 62.5       ,  74.75      ,  74.75      ],
       [ 64.26666667,  72.2       ,  71.        ],
       [ 63.15384615,  60.38461538,  57.84615385],
       [ 69.33333333,  66.        ,  69.        ],
       [ 54.66666667,  66.33333333,  69.66666667],
       [ 75.5       ,  74.        ,  68.5       ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 70.18181818,  65.45454545,  62.72727273],
       [ 77.        ,  90.        ,  84.        ],
       [ 53.        ,  65.25      ,  63.75      ],
       [ 64.26666667,  72.2       ,  71.        ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 73.5       ,  81.25      ,  85.25      ],
       [ 64.2       ,  60.        ,  58.        ],
       [ 51.5       ,  52.        ,  46.5       ],
       [ 69.        ,  71.        ,  65.        ],
       [ 79.        ,  89.        ,  89.        ],
       [ 69.33333333,  66.        ,  69.        ],
       [ 54.66666667,  66.33333333,  69.66666667],
       [ 70.875     ,  67.3125    ,  62.8125    ],
       [ 73.5       ,  81.25      ,  85.25      ],
       [ 52.        ,  39.5       ,  39.        ],
       [ 73.        ,  63.        ,  68.        ],
       [ 52.66666667,  61.16666667,  60.        ],
       [ 65.125     ,  70.5       ,  70.75      ],
       [ 66.07142857,  72.42857143,  74.14285714],
       [ 79.        ,  89.        ,  89.        ],
       [ 75.5       ,  72.5       ,  73.        ],
       [ 80.4       ,  79.        ,  82.4       ],
       [ 83.        ,  88.        ,  89.5       ],
       [100.        ,  96.        ,  86.        ],
       [ 67.75      ,  61.25      ,  58.75      ],
       [ 75.        ,  82.        ,  79.        ],
       [ 63.66666667,  63.83333333,  59.83333333],
       [ 57.66666667,  55.66666667,  50.        ],
       [ 82.66666667,  80.        ,  75.33333333],
       [ 75.33333333,  71.33333333,  72.5       ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 45.        ,  47.        ,  49.        ],
       [ 52.25      ,  50.5       ,  49.5       ],
       [ 68.5       ,  77.5       ,  77.2       ],
       [ 72.71428571,  68.71428571,  65.57142857],
       [ 67.5       ,  56.        ,  46.5       ],
       [ 50.        ,  56.        ,  54.        ],
       [ 70.18181818,  65.45454545,  62.72727273],
       [ 73.27272727,  68.72727273,  66.72727273],
       [ 48.75      ,  44.5       ,  39.75      ],
       [ 65.125     ,  70.5       ,  70.75      ],
       [ 65.125     ,  70.5       ,  70.75      ],
       [ 59.        ,  70.5       ,  71.5       ],
       [ 63.        ,  72.22222222,  72.33333333],
       [ 75.66666667,  64.        ,  60.66666667],
       [ 72.625     ,  77.        ,  77.125     ],
       [ 66.        ,  74.66666667,  78.66666667],
       [ 64.9       ,  57.9       ,  54.7       ],
       [ 57.        ,  68.        ,  73.        ],
       [ 70.625     ,  64.75      ,  60.625     ],
       [ 69.44444444,  80.        ,  83.11111111],
       [ 66.07142857,  72.42857143,  74.14285714],
       [ 66.57142857,  74.14285714,  74.42857143],
       [ 70.25      ,  83.5       ,  83.25      ],
       [ 69.44444444,  80.        ,  83.11111111],
       [ 72.71428571,  68.71428571,  65.57142857],
       [ 59.66666667,  71.        ,  70.        ],
       [ 72.        ,  79.        ,  82.        ],
       [ 52.25      ,  50.5       ,  49.5       ],
       [ 75.        ,  80.        ,  81.        ],
       [ 68.66666667,  60.33333333,  53.66666667],
       [ 72.625     ,  77.        ,  77.125     ],
       [ 57.        ,  64.        ,  65.5       ],
       [ 66.71428571,  62.85714286,  60.14285714],
       [ 59.66666667,  71.        ,  70.        ],
       [ 69.        ,  71.        ,  65.        ],
       [ 80.4       ,  79.        ,  82.4       ],
       [ 87.        ,  91.        ,  81.        ],
       [ 57.5       ,  63.        ,  58.        ],
       [ 62.4       ,  58.        ,  55.4       ],
       [ 70.875     ,  68.625     ,  65.375     ],
       [ 58.9       ,  68.1       ,  66.4       ],
       [ 64.26666667,  72.2       ,  71.        ],
       [ 53.        ,  65.25      ,  63.75      ],
       [ 58.5       ,  71.75      ,  67.75      ],
       [ 68.8       ,  64.2       ,  63.        ],
       [ 52.25      ,  50.5       ,  49.5       ],
       [ 52.        ,  56.5       ,  57.5       ],
       [ 59.75      ,  70.75      ,  71.        ],
       [ 83.33333333,  77.33333333,  72.33333333],
       [ 58.        ,  75.        ,  77.        ],
       [ 69.        ,  71.        ,  65.        ],
       [ 40.        ,  56.        ,  51.75      ],
       [ 69.44444444,  80.        ,  83.11111111],
       [ 72.6       ,  80.8       ,  80.4       ],
       [ 69.44444444,  80.        ,  83.11111111],
       [ 64.26666667,  72.2       ,  71.        ],
       [ 62.        ,  65.5       ,  67.25      ],
       [ 56.        ,  72.        ,  65.        ],
       [ 55.        ,  62.5       ,  56.        ],
       [ 52.        ,  39.5       ,  39.        ],
       [ 63.66666667,  63.83333333,  59.83333333],
       [ 70.25      ,  83.5       ,  83.25      ],
       [ 68.5       ,  77.5       ,  77.2       ],
       [ 77.2       ,  71.6       ,  69.8       ],
       [ 64.9       ,  57.9       ,  54.7       ],
       [ 48.5       ,  58.        ,  56.        ],
       [ 63.        ,  72.22222222,  72.33333333],
       [ 79.        ,  89.        ,  89.        ],
       [ 58.        ,  58.66666667,  58.66666667],
       [ 65.        ,  76.33333333,  73.33333333],
       [ 66.5       ,  77.25      ,  79.5       ],
       [ 72.625     ,  77.        ,  77.125     ],
       [ 69.57142857,  76.71428571,  80.14285714],
       [ 52.        ,  56.5       ,  57.5       ],
       [ 61.66666667,  69.33333333,  67.66666667],
       [ 52.66666667,  61.16666667,  60.        ],
       [ 58.4       ,  62.2       ,  61.8       ],
       [ 64.26666667,  72.2       ,  71.        ],
       [ 66.07142857,  72.42857143,  74.14285714],
       [ 53.        ,  65.25      ,  63.75      ],
       [ 77.6       ,  84.        ,  88.2       ],
       [ 79.        ,  79.        ,  78.        ],
       [ 80.4       ,  79.        ,  82.4       ],
       [ 68.        ,  75.        ,  73.        ],
       [ 75.33333333,  71.33333333,  72.5       ],
       [ 79.33333333,  74.66666667,  73.33333333],
       [ 66.        ,  76.5       ,  83.5       ]])

In [34]:
dtreg1.score(xtest,ytest)*100

c:\users\shivani\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:434: FutureWarning: The default value of multioutput (not exposed in score method) will change from 'variance_weighted' to 'uniform_average' in 0.23 to keep consistent with 'metrics.r2_score'. To specify the default value manually and avoid the warning, please either call 'metrics.r2_score' directly or make a custom scorer with 'metrics.make_scorer' (the built-in scorer 'r2' uses multioutput='uniform_average').
  "multioutput='uniform_average').", FutureWarning)

4.225982408643512